version: '3'

services:
  seeddb:
    build: ./database/postgresql
    depends_on:
      - 'database'
    links: 
      - database

  container:
    build: .
    depends_on:
      - 'seeddb'
    ports:
      - "80:3002"

  database:
    image: postgres:latest
    ports:
      - "54320:5432"